# Generated by Django 4.2.7 on 2023-11-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auther',
            old_name='biograph',
            new_name='biography',
        ),
    ]
